[workspace]
members = [
  "admin",
  "cargo-cyndra",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "service"
]
exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db"
]
