version: "3"
volumes:
  cyndra-backend-vol:
    external: true
services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/lib/cyndra/crates

        cat<<EOF > /var/lib/cyndra/users.toml
        [test-key]
        name = "tester"
        projects = []
        EOF

        mkdir -p $$CARGO_HOME
        cat<<EOF > $$CARGO_HOME/config.toml
        [patch.crates-io]
        cyndra-service = { path = "/usr/src/cyndra/service" }
        EOF

        exec /usr/local/bin/service "$${@:0}"
    volumes:
      - .:/usr/src/cyndra
  provisioner:
    extends:
      file: docker-compose.yml
      service: provisioner
  db:
    extends:
      file: docker-compose.yml
      service: db
