#cloud-config

# Install needed packages
packages:
  - docker.io
  - nfs-common

# Create the docker group
groups:
  - docker

# Add default auto-created user to docker group
system_info:
  default_user:
    groups: [docker]

# Create our systemd files
write_files:
  - encoding: b64
    content: ${opt_cyndra_content}
    path: /lib/systemd/system/opt-cyndra.mount
    owner: root:root
    permissions: "0644"
  - encoding: b64
    content: ${cyndra_backend_content}
    path: /lib/systemd/system/cyndra-backend.service
    owner: root:root
    permissions: "0644"

power_state:
  mode: reboot

# Up services on every boot
runcmd:
  - [systemctl, enable, "opt-cyndra.mount"]
  - [systemctl, enable, "cyndra-backend.service"]
