[package]
name = "cyndra-admin"
version = "0.50.0"
edition = "2021"
publish = false

[dependencies]
cyndra-api-client = { workspace = true, default-features = true }
cyndra-common = { workspace = true, features = ["models"] }
cyndra-backends = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
dirs = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = ["default", "env-filter"] }
